version: "3.7"
services: 
    angular-frontmadsis:
        build:
            context: .
            dockerfile: angular.dockerfile
            args:
                AMBIENTE: "PRODUCCION"
                APACHE: "www-data"
                USER: ${USER}
                CUSTOMUID: $CUSTOMUID
                CUSTOMGID: $CUSTOMGID
        container_name: angular-frontmadsis
        environment:
            - TZ=America/Guayaquil
        volumes:
            - ~/.ssh/:/root/.ssh/
        networks: 
            raul_network:
                aliases: 
                    - angular-frontmadsis    
        ports:
            - "4400:4400"
            - "4500:4500"
            - "9222:9222"          
        tty: true
networks: 
    raul_network:
        name: raul_net
        driver: bridge
        ipam:
            driver: default